env:
  es6: true
  node: true
extends:
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins:
  - vue
rules: {}
